kind: Service
apiVersion: v1
metadata:
  name: aspnetapp
  labels:
    app: aspnet
spec:
  selector:
    app: aspnet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp
  labels:
    app: aspnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet
  template:
    metadata:
      labels:
        app: aspnet
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "aspnetapp"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: aspnet
        image: hello-k8s-aspnet:latest
        env:
        - name: APP_PORT
          value: "3000"
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent